name: ❓ Question / Support
description: Ask a question or request help
title: "[Question] "
labels: [question]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide background or why this is important.

  - type: textarea
    id: tried
    attributes:
      label: What I’ve Tried
      description: Docs, steps, or resources you've already checked.
